using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NativeDCB.Sdk.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class SchemaGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<SchemaType> events = Schemas(
            context, "NativeDCB.Sdk.Schemas.EventTypeAttribute", isEvent: true);
        IncrementalValuesProvider<SchemaType> commands = Schemas(
            context, "NativeDCB.Sdk.Schemas.CommandTypeAttribute", isEvent: false);
        context.RegisterSourceOutput(
            events.Collect().Combine(commands.Collect()),
            static (productionContext, schemas) => Emit(productionContext, schemas.Left, schemas.Right));
    }

    private static IncrementalValuesProvider<SchemaType> Schemas(
        IncrementalGeneratorInitializationContext context,
        string attributeName,
        bool isEvent)
    {
        return context.SyntaxProvider.ForAttributeWithMetadataName(
            attributeName,
            static (node, _) => node is TypeDeclarationSyntax,
            (attributeContext, _) => new SchemaType(
                ((INamedTypeSymbol)attributeContext.TargetSymbol).ToDisplayString(
                    SymbolDisplayFormat.FullyQualifiedFormat),
                attributeContext.Attributes[index: 0].ConstructorArguments[index: 0].Value as string ?? string.Empty,
                isEvent));
    }

    private static void Emit(
        SourceProductionContext context,
        IReadOnlyList<SchemaType> events,
        IReadOnlyList<SchemaType> commands)
    {
        SchemaType[] schemas = events.Concat(commands)
            .Distinct()
            .OrderBy(value => value.Name, StringComparer.Ordinal)
            .ThenBy(value => value.TypeName, StringComparer.Ordinal)
            .ToArray();
        StringBuilder source = new(value: """
                                          // <auto-generated />
                                          namespace NativeDCB.Generated;

                                          public static class NativeDcbGeneratedSchemas
                                          {
                                              public static global::System.Collections.Generic.IReadOnlyList<global::NativeDCB.Sdk.Schemas.SchemaDescriptor> Create()
                                              {
                                                  return new global::NativeDCB.Sdk.Schemas.SchemaDescriptor[]
                                                  {

                                          """);
        foreach (SchemaType schema in schemas)
        {
            source.Append("            global::NativeDCB.Sdk.Schemas.SchemaDescriptor.")
                .Append(schema.IsEvent ? "ForEvent" : "ForCommand")
                .Append(value: '<').Append(schema.TypeName).AppendLine(">(),");
        }

        source.AppendLine(value: """
                                         };
                                     }
                                 }
                                 """);
        context.AddSource("NativeDcbGeneratedSchemas.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private sealed record SchemaType(string TypeName, string Name, bool IsEvent);
}