<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NativeDCB.Engine\NativeDCB.Engine.csproj" />
    <ProjectReference Include="..\NativeDCB.Model\NativeDCB.Model.csproj" />
    <ProjectReference Include="..\NativeDCB.Ndl\NativeDCB.Ndl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Server" Version="10.2.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NativeDCB.Engine.Tests" />
    <InternalsVisibleTo Include="NativeDCB.MicroBenchmarks" />
    <InternalsVisibleTo Include="NativeDCB.Server.IntegrationTests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
