<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NativeDCB.Commerce\NativeDCB.Commerce.csproj" />
    <ProjectReference Include="..\..\..\src\NativeDCB.Sdk\NativeDCB.Sdk.csproj" />
  </ItemGroup>
</Project>
